### ISSUE TITLE
UI Kit: Tables

### ISSUE THREAD

**Issue by mgdhs** [govCMS/ui-kit-base-theme#25]
As a site owner, I want my site's tables to use the UI toolkit's table style, so that my user's get a nice consistent experience with nice looking tables.

Acceptance criteria
- [ ] By default all tables should get it, so publishers don't have to add a class
- [ ] Drupal's sorting should still function and be accessible
- [ ] Investigate if their table style works with our more complex tables

The views-specific table code can be removed.

**Comment by DJMyles** [comment]
@mgdhs this is a very tricky one in terms of meeting ``` By default all tables should get it, so publishers don't have to add a class ```

the `<table>` element itself comes with next to no styling with the table class selector providing the core of the look and feel. For example:

http://guides.service.gov.au/design-guide/components/tables/index.html

A basic table without any classes looks like:

<img width="849" alt="screen shot 2016-12-19 at 10 36 48 am" src="https://cloud.githubusercontent.com/assets/14192426/21297609/281cc9f8-c5d7-11e6-8c90-75f650b70acc.png">

once you add a `class="content-table"` it grabs that and looks like:

<img width="830" alt="screen shot 2016-12-19 at 10 38 32 am" src="https://cloud.githubusercontent.com/assets/14192426/21297620/55100560-c5d7-11e6-909b-77d057547454.png">

Do you think we should be having a discussion with DTA / community around shifting the bulk of the basic styling to the `<table>` element itself rather than using classes, reserving those for more complex table types? Essentially `.content-table` becomes the default without a class, however this would invovle us making the change on our end then progressing it via a pull request upstream.

Thoughts @rujiali @Feng-Shui

**Comment by mgdhs** [comment]
See comment in PR.

**Comment by DJMyles** [comment]
Merged

**Comment by DJMyles** [comment]
@mgdhs see comments by @rujiali in the PR

**Comment by rujiali** [comment]
Sorry guys. Have to reopen the issue as I'm having a slightly different view on this. https://github.com/govCMS/ui-kit-base-theme/pull/26#issuecomment-268102526

**Comment by mgdhs** [comment]
@rujiali this was discussed a bit in the face to face meeting with the DTA. They are likely to class _everything_ in 2.0. It is therefore unlikely they'll change this. We're only going to see more like this.

How they've done this table by a class wouldn't work for how we all run our websites. We have publishers entering content, possibly hundreds of times a day. What we're doing is implementing the UI toolkit into our CMS and websites. Some of that is going be to extending and tweaking the UI toolkit so it works for us.

The alternative would be to process the content from the WYSIWYG as it is saved or output and adding the class. That seems a lot harder than this solution.

The only change I'd suggest is we change it to `table:not(.table-plain) { @extend .content-table; }` which adds a bit of flexibility so it can be overridden if someone really wants to.

I like that you've disagreed :) If you still disagree, and I'm happy if you do, how do we resolve this? Is there someone or a group that can arbitrate or decide? I'm struggling to think who that might be.

**Comment by rujiali** [comment]
@mgdhs thanks for the explanation. I fully understand your situation. And extending the class to table tag will **NOT** affect us.
But in my opinion:

1. We can not care of what the author input in the text area, as they can put in a uncompleted html that breaks the whole site. 
2. With your situation, yes, the author needs to put the tables in, and I agreed that we can not expect them to manually put the class name in each table. The solution looks good to me. But I think this needs to happen in the sub theme level, not the base theme. As the base theme means to just to take what the UI KIT offers. 

Understanding we all have deadline :) There is no point wasting our time on this. I'm happy to pass on, since it is already merged anyway. But maybe leave the issue postpone, and we can continue the conversation when we have time in future.

**Comment by mgdhs** [comment]
@rujiali while a sub-theme would work, I'd like to get this theme to be pretty good for most users. That will save everyone from developing the same functions and changes in their sub-theme. Personally, that part makes it quite exciting for me, because we can make things work properly out of the box, with sane defaults.

Maybe it would be worth using this to clarify our goals for the theme. That way we're all on the same page. I'll chuck something on the wiki as a starting point tomorrow.

**Comment by DJMyles** [comment]
Closing as we can always bring this up at a later time as part of a broader conversation.
