### ISSUE TITLE
UI KIT: Media query is causing some elements to wrap unnecessarily and not use 100% width

### ISSUE THREAD

**Issue by DJMyles** [govCMS/ui-kit-base-theme#35]
See screenshot however this should not be happening. We should be letting these elements use the 100% width of the container and not be setting arbitrary max-widths for them. The result is like the H1 in the screenshot where it wraps instead of making full use of the content area.

<img width="1344" alt="screen shot 2017-01-09 at 9 24 44 am" src="https://cloud.githubusercontent.com/assets/14192426/21754124/e548c870-d64d-11e6-82a4-748046d69310.png">

**Comment by DJMyles** [comment]
After speaking to Michael, this is for readability and line length purposes.

The ui kit does supply a 100% width class however that needs to be applied to individual elements within the content area.

Leaving it as default causes whitespace to the left and right (depending on what sidebars are active). It's subjective but it could look strange.

**Comment by dlm78** [comment]
Yes, this is intentional for readability and applies to typographic elements. If it's killing your layout you can apply `.content-full-width` to an element to force full width. Given that the wrapping is dependent on `.content-main`, you could create a modifier such as `.content-main--full-width` to extend that class. That would negate the need to apply to every element.

**Comment by Feng-Shui** [comment]
@DJMyles as this is as designed in the UI Kit, suggest that we close this issue as this can be addressed in sub-themes as required?

**Comment by DJMyles** [comment]
Closing to address in sub theme
