### ISSUE TITLE
UI Kit: Forms

### ISSUE THREAD

**Issue by Feng-Shui** [govCMS/ui-kit-base-theme#7]
No user story here, user just wants to be able to use forms.

https://gov-au-ui-kit.apps.staging.digital.gov.au/section-forms.html

---

If we need to add classes to FAPI elements, we can use [theme_form_element](https://api.drupal.org/api/drupal/includes%21form.inc/function/theme_form_element/7.x).  Drupal 7 doesn't support HTML5 form elements out of the box, but the [Elements](https://www.drupal.org/project/elements) module provides them, so any HTML5 styling need to remain intact.

UI Kit styling has help/description text above the form element below the label.  It also recommends that colons be dropped from labels.  The documentation above should be reviewed to ensure that all recommendations are implemented.

**Comment by Feng-Shui** [comment]
@rujiali has mentioned there's an issue where Drupal's `required` class picks up error styling from the UI Kit.  We're going to need to resolve this.

**Comment by rujiali** [comment]
By default, the browser will validate the required (the attribute 'required') input when loading the page and add the pseudo class ':invalid' to the element. This is not a Drupal specific behaviour. The UI KIT has the style of `input:invalid { outline: red; }`, which will pick up all the required inputs when loading the page. I don't think there is anything we can do in the Drupal level to fix this issue. 

I would propose to override the UI KIT style, instead of colouring the outline for :invalid, we colour the '*' in the label area. 

The UI KIT does have the style for 'invalid' class, so we don't need to worry about the processed invalid form. Thoughts ? @Feng-Shui

**Comment by Feng-Shui** [comment]
Yeah ok, I misunderstood the issue.

Looking at the markup on [the guide](https://gov-au-ui-kit.apps.staging.digital.gov.au/section-forms.html#guide-forms-1-text-input), the invalid element is getting styling from an `.invalid` class.  If we remove the pseudo class in the UI Kit, can we just rely on that class?

**Comment by rujiali** [comment]
Yes, I added `.invalid` class in preprocess_form_element to any element with `.required .error` classes. The style will apply to the elements after Drupal does the validation. 

Since this will require custom style overriding `:invalid` pseudo class, do we agree with the proposed solution?

**Comment by rujiali** [comment]
This issue is blocked as the UI KIT is **NOT** using the default input for the radio button and checkboxes. Instead, it sets left: -10000px to the origin radio button and checkbox, and uses 'before' to style the 'circle' input. The browser can **NOT** pop up message and highlight the required 'circle' field in this way. 
This is a bug from the UI KIT that we may need to raise to the DTA.

**Comment by klepas** [comment]
Just reading over the convo, and have 2 points:

Re. optional vs required fields, [we recommend against the usage of asterisks](http://guides.service.gov.au/components/forms-buttons/index.html#optional-mandatory-fields):

> Only ask for the information you absolutely need. Don't mark mandatory fields with asterisks.
> 
> If you have to ask for optional information mark the field labels with ‘(optional)’.

Regarding how we’re styling the radio buttons and checkboxes:

> This issue is blocked as the UI KIT is **NOT** using the default input for the radio button and checkboxes. Instead, it sets left: -10000px to the origin radio button and checkbox, and uses 'before' to style the 'circle' input. The browser can **NOT** pop up message and highlight the required 'circle' field in this way.

Hhhm. Yea, that’s not pretty. I think we stole this from [GDS’ implementation](https://govuk-elements.herokuapp.com/form-elements/#form-radio-buttons) (which has changed again; they’re now super-imposing the custom styles and setting the system ones to `opacity: 0`).

> This is a bug from the UI KIT that we may need to raise to the DTA.

Yea, I would probably accept this as a bug — please feel free to open one.

FWIW: 2.x will see these re-done, likely in the way that they are implemented by Dom in [Westpac’s GEL](https://gel.westpacgroup.com.au/GUI/WBC/forms/#checkboxes).

**Comment by Feng-Shui** [comment]
I've got a work around for the issues with checkboxes which I'll run with for now to get things working.

**Comment by Feng-Shui** [comment]
@rujiali going to assign myself to this one given your busy sub-themeing.  Do you have any forms on any of the sites that your launching in the next few weeks?

**Comment by rujiali** [comment]
Yes, we have a form we are going to lunch. Currently I'm using css to fix issue in our sub theme. Feel free to assign it to you.

**Comment by Feng-Shui** [comment]
This has all been implemented/resolved in `feature/markup-review`.

PR will be coming.

**Comment by Feng-Shui** [comment]
PR #52

**Comment by Feng-Shui** [comment]
Merged
