### ISSUE TITLE
UI Kit: Grid

### ISSUE THREAD

**Issue by Feng-Shui** [govCMS/ui-kit-base-theme#8]
**As a user
I want a responsive, mobile first grid
So I can consume content on my mobile phone, tablet and desktop**

https://gov-au-ui-kit.apps.staging.digital.gov.au/section-grid.html

---

This task will be the integration of the UI Kit grid classes in the page and region templates.

- Given that breakpoints should be based on site content, we're going to need provide some good instructions on how to customise breakpoints in sub-themes.
- Need to make sure we have viewport tags set

**Comment by Feng-Shui** [comment]
@rujiali @DJMyles given you have both worked on this, suggest you work on this together to compare notes?

**Comment by DJMyles** [comment]
@rujiali @Feng-Shui yep this is an interesting one.

I'm inclined to essentially extend out to bootstrap classes TBH but it's a broader conversation.

**Comment by rujiali** [comment]
Moving the conversation here: 
@rujiali I suspect that could be the case. Maybe the logic in page.tpl.php needs to be something like:

if no sidebar -> 16 of 16 columns for main
if sidebar left -> float left (and use 4 cols) -> main = 12 cols
if sidebar right -> float right (and use 4 cols) -> main = 12 cols

The class attached to the `<main>` element (as per toolkit) determines if it is left or right ( `.siderbar-has-controls`)

I wonder if there is also a business a case where both left and right sidebars might be used at once, in which case it would be main -> 8 cols and each respective sidebar 4 cols.

cc @Feng-Shui

**Comment by Feng-Shui** [comment]
Re the business case for two sidebars, we do have a few instances of that at the moment, but can live with one sidebar if needed.

Re the sidebar/no-sidebar: what classes control the width/column count of the main area and sidebars?

**Comment by DJMyles** [comment]
I believe column width is dictated by the breakpoints you set in grid settings and then calculated by how many columns are set for that specific breakpoint. See ui-kit/assets/sass/utils/_grid-settings.scss

> Primary content is always contained in 12 columns. This allows for seamless introduction of a sidebar/side navigation.
> 
> The grid unit proportions, gutters and spacing are defined in `_grid-settings.scss`.

I don't fully understand it TBH but I don't think it's working properly at the moment. We probably need it up and running sooner rather than later so that we can fully test stuff like navs and list styles within other regions which is currently blocked.

**Comment by rujiali** [comment]
There is no class to indicate the grid unfortunately. I was setting the grid for particular page in my custom scss. And the UI KIT does not support two sidebars on the right and left. 
I guess we have following options:

1.  Leave the layout and grid what it is, use the custom style in subtheme to alter the grid for certain pages
2. Create classes to indicate the grid and use preprocess to do the condition check and assignment
3. We don't support 2 sidebars on both sides, leave the styling to the subtheme
4. We add style in the base theme ourselves to support 2 sidebars on both sides.

My preferences: 2, 3.

**Comment by rujiali** [comment]
Question: we don't support user uploaded logo ? @Feng-Shui

**Comment by DJMyles** [comment]
@rujiali @Feng-Shui Given our chat last week combined with the subsequent DTA chatter on slack, it looks as if we will get exactly what we want. Watch this space I guess :)

**Comment by klepas** [comment]
Hey y’all.

We had a chat about this and decided pretty much on the following:

- we will provide a flexible grid system available via classes in 2.x
- we recommend peeps use something like https://gist.github.com/johnkoht/6405117 in the interim if you want fine-tuned control

In the meantime, I apologise for the pain points around the grid system — fwiw, we made most of these decisions while our scope was just for gov.au, and did not have a chance to properly revisit it since our remit changed. A lot of the assumptions we made around front enders having control of the markup produced, etc. are rather different now.

A brief note re the left-hand sidebar (the `has-controls` one) — this was intended to only house view control options, eg. filtering options that live reload results on a page, and not for navs themselves. We will definitely revisit this in 2.x.

Let us know if we can help further.

**Comment by Feng-Shui** [comment]
@DJMyles @rujiali I think we're going to need to get an interim solution in place before 2.x hits.

@DJMyles do you want to take the above bootstrap/bourbon neat mashup for a spin?

**Comment by Feng-Shui** [comment]
Just to keep this issue up-to-date @mgdhs was working on some code yesterday that would allow the user to bootstrap style classes within content areas.  For things like Panels/DS templates we can use the Neat grid stuff because we (as developers) will be adding CSS for those.

@DJMyles @rujiali for the page layout, I'm happy to do some work on this to get left and right sidebars working with content regions in Drupal based on class names in `template.php` and then drop in the sass to make this work.  This is inline with the approach @rujiali outlined [above](#issuecomment-267196778).

We happy with this approach?

**Comment by DJMyles** [comment]
@Feng-Shui no issues here

**Comment by rujiali** [comment]
Happy with the solution. @Feng-Shui
